server:
    port: 9090

datasource:
    mysql:
        url: jdbc:mysql://192.168.2.206:3306
        username: jjgonzalez
        password: Desarrollo.2022
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        dialect: org.hibernate.dialect.MySQL8Dialect
        showsql: true
